name: personal-blog
on:
  push:
    branches:
      - master
    paths-ignore: # 下列文件的变更不触发部署
      - README.md
      - LICENSE
      - .gitignore
      - scripts
  pull_request:
    branches:
      - master
    paths-ignore: # 下列文件的变更不触发部署
      - README.md
      - LICENSE
      - .gitignore
      - scripts
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout # 1. 将仓库内master分支的内容下载到工作目录
      uses: actions/checkout@v2
    - name: Install # 2. 安装依赖
      run: pnpm
    - name: Build   # 3. 打包
      run: pnpm build
    - name: Deploy to Server # 4. 推到服务器
      uses: easingthemes/ssh-deploy@v2.1.5
      env:
          SSH_PRIVATE_KEY: ${{ secrets.BLOGKEY }}
          ARGS: '-avz --delete --exclude *.js.map'
          SOURCE: './docs/.vuepress/dist'
          REMOTE_HOST: ${{ secrets.BLOGHOST }}
          REMOTE_USER: ${{ secrets.BLOGUSER }}
          TARGET: ${{ secrets.BLOGPATH }}