name: personal-blog
on:
  push:
    branches:
      - master
    paths-ignore: # 下列文件的变更不触发部署
      - README.md
      - LICENSE
      - .gitignore
      - scripts
  pull_request:
    branches:
      - master
    paths-ignore: # 下列文件的变更不触发部署
      - README.md
      - LICENSE
      - .gitignore
      - scripts
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install
      run: npm install -g pnpm@7.18.1 && pnpm install
    - name: Build
      run: pnpm build
    - name: Deploy to Server
      uses: easingthemes/ssh-deploy@v2.1.5
      env:
          SSH_PRIVATE_KEY: ${{ secrets.BLOGKEY }}
          ARGS: '-avz --delete --exclude *.js.map'
          SOURCE: './docs/.vuepress/dist'
          REMOTE_HOST: ${{ secrets.BLOGHOST }}
          REMOTE_USER: ${{ secrets.BLOGUSER }}
          TARGET: ${{ secrets.BLOGPATH }}